title: The Sims 1 Object Encyclopedia
description: A catalog of classic items.
baseurl: "/TheSims1Encyclopedia"
url: "https://changeallthetime123-debug.github.io"

# Define the custom collection for objects
collections:
  objects:
    output: true
