title: The Sims 1 Object Encyclopedia
description: A catalog of classic items.
baseurl: "/objects" 
url: "https://yourusername.github.io"

# Define the custom collection for objects
collections:
  objects:
    output: true
