title: The Sims 1 Object Encyclopedia
description: A catalog of classic items.
baseurl: "/TheSims1Encyclopedia"
url: "https://changeallthetime123-debug.github.io"

collections:
  objects:
    output: true
    permalink: /objects/:title/
